# Generated by Django 6.0.2 on 2026-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('General Medicine', 'General Medicine'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Gynecology', 'Gynecology'), ('Urology', 'Urology'), ('Oncology', 'Oncology'), ('Anesthesiology', 'Anesthesiology'), ('Nephrology', 'Nephrology'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Rheumatology', 'Rheumatology'), ('General Surgery', 'General Surgery')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
