# Generated by Django 6.0.3 on 2026-04-01 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribeMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('1-1-1', '1-1-1'), ('0-1-1', '0-1-1'), ('1-0-1', '1-0-1'), ('1-1-0', '1-1-0'), ('0-0-1', '0-0-1'), ('0-1-0', '0-1-0'), ('1-0-0', '1-0-0')], max_length=7)),
                ('dosage', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'prescribe_medicine',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text='Patient complaints')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False, help_text='True if consultation is locked for further changes.')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='receptionist.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescribeLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_prescriptions', to='doctor.consultation')),
            ],
            options={
                'db_table': 'prescribe_lab',
            },
        ),
    ]
