# Generated by Django 6.0.3 on 2026-04-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('lab_tech', '0001_initial'),
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribelab',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab_tech.labtest'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lab_tests',
            field=models.ManyToManyField(through='doctor.PrescribeLab', to='lab_tech.labtest'),
        ),
        migrations.AddField(
            model_name='prescribemed',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_prescriptions', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='prescribemed',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacist.medicine'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medicines',
            field=models.ManyToManyField(through='doctor.PrescribeMed', to='pharmacist.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='prescribelab',
            unique_together={('consultation', 'lab_test')},
        ),
        migrations.AlterUniqueTogether(
            name='prescribemed',
            unique_together={('consultation', 'medicine')},
        ),
    ]
