# Generated by Django 6.0.3 on 2026-04-01 14:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the lab test', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the test', null=True)),
                ('min_range', models.DecimalField(decimal_places=2, help_text='Minimum normal range value', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_range', models.DecimalField(decimal_places=2, help_text='Maximum normal range value', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the test', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Availability status of the test', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'db_table': 'lab_test',
                'ordering': ['test_name'],
            },
        ),
        migrations.CreateModel(
            name='LabBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for all lab tests', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', help_text='Current payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(help_text='Reference to the consultation that generated these lab tests', on_delete=django.db.models.deletion.CASCADE, related_name='lab_billing', to='doctor.consultation')),
            ],
            options={
                'verbose_name': 'Lab Billing',
                'verbose_name_plural': 'Lab Billings',
                'db_table': 'lab_billing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual test result value', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_abnormal', models.BooleanField(default=False, help_text='Flag indicating if result is outside normal range')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments about the test result', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', help_text='Status of the lab report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_prescription', models.ForeignKey(help_text='Reference to the lab prescription from doctor', on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='doctor.prescribelab')),
                ('test', models.ForeignKey(help_text='The lab test being performed', on_delete=django.db.models.deletion.PROTECT, related_name='lab_reports', to='lab_tech.labtest')),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'db_table': 'lab_report',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lab_prescription', 'test'), name='unique_lab_report_per_prescription_test')],
            },
        ),
    ]
